stages:
  - build
  - run

build:
  stage: build
  image: maven:3-jdk-8
  script:
  - java -version
   - cd PetriNetwork/
   - mkdir bin
   - javac -d bin/ src/main/java/mapd/exceptions/* src/main/java/mapd/interfaces/* src/main/java/mapd/implementations/*
  artifacts:
    paths:
     - bin/

run:
  stage: run
  image: maven:3-jdk-8
  script:
  - java -version
  - cd PetriNetwork/bin/
  - echo Running Main
  - java mapd.implementations.Main

  



